
POST http://localhost:3333/api/users/create-user HTTP/1.1
Content-Type: application/json

{
    "firstname": "Хап",
    "lastname": "Хап",
    "avatar": "https://avatars.mds.yandex.net/get-yapic/0/0-0/islands-middle",
    "email": "663674345@mail.ru",
    "jobTitle": "manager",
    "status": 100,
    "startDate": "2011-10-05T14:48:00.000Z"
}

###

GET http://localhost:3333/api/users/64d61425912a275376b5929c HTTP/1.1
Content-Type: application/json

###

DELETE  http://localhost:3333/api/users/delete/64d268fd6601fa6f295e66d1 HTTP/1.1
Content-Type: application/json

###