version: '3.5'
services:
  adaptation.backend.mongodb:
    image: mongo:latest
    container_name: adaptation.backend.mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: adaptation-backend
    ports:
      - 27017:27017
    volumes:
      - adaptation.backend.volume:/data/db
    networks:
      - adaptation.backend.network

  adaptation.backend:
    container_name: adaptation.backend
    depends_on:
      - adaptation.backend.mongodb
    restart: always
    image: adaptation.backend:latest
    environment:
      PORT: 3333
      MONGO_DB: backend
      MONGO_HOST: adaptation.backend.mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: test
      MONGO_DB_BASE: admin
    ports:
      - 3333:3333
    networks:
      - adaptation.backend.network

  rabbitmq: 
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '1080:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # fakesmtp:
  #   image: gessnerfl/fake-smtp-server
  #   container_name: "fakesmtp"
  #   hostname: "fakesmtp"
  #   ports:
  #     - "5025:5025"
  #     - "1081:5080"

  adaptation.notify.mongodb:
    image: mongo:latest
    restart: always
    container_name: adaptation.notify.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: adaptation-notify
    ports:
      - 27018:27017
    volumes:
      - adaptation.notify.volume:/data/db
    networks:
      - adaptation.notify.network
  
  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - adaptation.backend.mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@adaptation.backend.mongodb:27017/
    networks:
     - adaptation.backend.network

  mongo.express.notify:
    image: mongo-express
    restart: always
    container_name: mongo-express-notify
    depends_on:
      - adaptation.notify.mongodb
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@adaptation.notify.mongodb:27017/
    networks:
     - adaptation.notify.network

  adaptation.notify:
    container_name: adaptation.notify
    depends_on:
      - adaptation.notify.mongodb
    restart: always
    image: adaptation.notify:latest
    environment:
      PORT: 3334
      RABBIT_USER: admin
      RABBIT_PASSWORD: test
      RABBIT_HOST: localhost:5672
      RABBIT_NOTIFY_SERVICE_QUEUE: adaptation.notify
      MONGO_DB: adaptation-notify
      MONGO_HOST: adaptation.notify.mongodb
      MONGO_PORT: 27018
      MONGO_USER: admin
      MONGO_PASSWORD: test
      MONGO_DB_BASE: admin
      MAIL_SMTP_HOST: smtp.mail.ru
      MAIL_SMTP_PORT: 465
      MAIL_USER_NAME: adaptation.petrovich@mail.ru
      MAIL_USER_PASSWORD: tKbuiZXAHMfngdXykQLD
      MAIL_FROM: adaptation.petrovich<adaptation.petrovich@mail.ru>
    networks:
      - adaptation.notify.network
  
networks:
  adaptation.backend.network:
    driver: bridge
  adaptation.notify.network:
    driver: bridge

volumes: 
  adaptation.backend.volume:
  adaptation.notify.volume: