version: '3.5'
services:
  adaptation.backend.mongodb:
    image: mongo:latest
    container_name: adaptation.backend.mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: adaptation-backend
    ports:
      - 27017:27017
    volumes:
      - adaptation.backend.volume:/data/db
    networks:
      - adaptation.backend.network

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - adaptation.backend.mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@adaptation.backend.mongodb:27017/
    networks:
     - adaptation.backend.network

  adaptation.backend:
    container_name: adaptation.backend
    depends_on:
      - adaptation.backend.mongodb
    restart: always
    image: adaptation.backend:latest
    environment:
      PORT: 3333
      MONGO_DB: backend
      MONGO_HOST: adaptation.backend.mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: test
      MONGO_DB_BASE: admin
    ports:
      - 3333:3333
    networks:
      - adaptation.backend.network

networks:
  adaptation.backend.network:
    driver: bridge

volumes: 
  adaptation.backend.volume: