version: '3.5'
services:

  backend.mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .adaptation.backend.mongodb.env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/backend --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    networks:
      - adaptation.backend.network

  backend:
    container_name: backend
    depends_on:
      - backend.mongodb
    restart: always
    image: adaptation.backend:latest
    env_file:
      - .adaptation.backend.env
    ports:
      - 3333:3333
    networks:
      - adaptation.backend.network

networks:
  adaptation.backend.network:
    driver: bridge

volumes:
  org.backend.volume: